import {useEffect,useState} from 'react';
import {Home,ShoppingCart,Package,Boxes,Truck,Users,Wallet,Calculator,BarChart3,ClipboardList,Database,ChevronRight,LogOut,PanelLeft,RefreshCw,Search,Plus,X} from 'lucide-react';
import {getSqliteDb,persistDb,downloadSqliteBackup} from './database/sqliteDb';
type Product={id:number;code:string;name:string;category:string;priceUsd:number;stock:number;tax:number};
const modules:any[]=[['Inicio',Home],['Punto de Venta',ShoppingCart],['Ventas',ClipboardList],['Productos',Package],['Inventario',Boxes],['Compras',Truck],['Clientes',Users],['Proveedores',Users],['CxC',Wallet],['CxP',Wallet],['Caja y Bancos',Calculator],['Contabilidad',BarChart3],['Reportes',ClipboardList],['Configuración',Database]];
export default function App(){
 const [active,setActive]=useState('Inicio'); const [products,setProducts]=useState<Product[]>([]); const [query,setQuery]=useState(''); const [cart,setCart]=useState<Product[]>([]); const [rate,setRate]=useState(62.5); const [ready,setReady]=useState(false);
 useEffect(()=>{getSqliteDb().then(db=>{const rows=db.exec('SELECT id,code,name,category,priceUsd,stock,tax FROM products ORDER BY name')[0]?.values||[];setProducts(rows.map((r:any)=>({id:Number(r[0]),code:String(r[1]),name:String(r[2]),category:String(r[3]),priceUsd:Number(r[4]),stock:Number(r[5]),tax:Number(r[6])})));const c=db.exec('SELECT rate FROM company LIMIT 1')[0]?.values[0]?.[0];if(c)setRate(Number(c));setReady(true)})},[]);
 const filtered=products.filter(p=>(p.code+' '+p.name+' '+p.category).toLowerCase().includes(query.toLowerCase())); const total=cart.reduce((s,p)=>s+p.priceUsd,0);
 return <div className='h-screen flex bg-slate-950 text-slate-100'>
 <aside className='w-64 bg-slate-900 border-r border-slate-700 flex flex-col'><div className='p-4 border-b border-slate-700'><div className='text-xl font-black'>SIFER<span className='text-cyan-400'>360</span></div><div className='text-[10px] text-slate-400 uppercase'>Administrativo · Web</div></div>
 <nav className='p-2 flex-1 overflow-auto'>{modules.map(([name,Icon])=><button key={name} onClick={()=>setActive(name)} className={'w-full flex items-center gap-3 px-3 py-2.5 rounded text-sm mb-1 '+(active===name?'bg-cyan-500/15 text-cyan-300 border border-cyan-500/30':'text-slate-300 hover:bg-slate-800')}><Icon size={17}/><span>{name}</span>{active===name&&<ChevronRight size={14} className='ml-auto'/>}</button>)}</nav>
 <div className='p-3 border-t border-slate-700 text-xs text-slate-400'>Usuario: <b className='text-slate-200'>Administrador</b><div className='mt-2 flex items-center gap-2'><LogOut size={14}/>Cerrar sesión</div></div></aside>
 <main className='flex-1 min-w-0 flex flex-col'><header className='h-14 border-b border-slate-700 bg-slate-900 flex items-center px-5 gap-4'><PanelLeft size={18}/><b>{active}</b><div className='ml-auto flex items-center gap-4 text-xs'><span className='px-2 py-1 rounded bg-emerald-500/10 text-emerald-300'>{ready?'BD local activa':'Inicializando BD…'}</span><span>BCV <b className='font-mono text-cyan-300'>Bs. {rate.toFixed(2)}</b></span><button onClick={()=>{persistDb();location.reload()}}><RefreshCw size={16}/></button></div></header>
 <div className='flex-1 overflow-auto p-5'>{active==='Punto de Venta'?<POS cart={cart} setCart={setCart} total={total} rate={rate}/>:active==='Productos'?<Products products={filtered} query={query} setQuery={setQuery} add={(p:Product)=>{setCart(c=>[...c,p]);setActive('Punto de Venta')}}/>:<Dashboard active={active} products={products} cart={cart} setActive={setActive} backup={downloadSqliteBackup}/>}</div></main></div>}
function Dashboard({active,products,cart,setActive,backup}:any){return <><div className='mb-6'><div className='text-2xl font-black'>{active}</div><div className='text-sm text-slate-400 mt-1'>DISTRIBUIDORA SIFER 360, C.A. · sistema administrativo estilo a2 Softway</div></div><div className='grid grid-cols-2 xl:grid-cols-4 gap-4'>{[['Productos',products.length,Package],['Stock total',products.reduce((a:number,p:Product)=>a+p.stock,0),Boxes],['Ticket en espera',cart.length,ShoppingCart],['Base de datos','SQLite',Database]].map(([n,v,I]:any)=><div className='bg-slate-900 border border-slate-700 rounded-lg p-5' key={n}><I className='text-cyan-400 mb-4' size={22}/><div className='text-xs text-slate-400 uppercase'>{n}</div><div className='text-2xl font-black mt-1'>{v}</div></div>)}</div><div className='mt-5 grid lg:grid-cols-2 gap-5'><section className='bg-slate-900 border border-slate-700 rounded-lg p-5'><h2 className='font-bold mb-4'>Accesos rápidos</h2>{['Punto de Venta','Productos','Inventario','Ventas','CxC','CxP'].map(x=><button onClick={()=>setActive(x)} key={x} className='mr-2 mb-2 px-4 py-3 bg-slate-800 rounded border border-slate-700 text-sm'>{x}</button>)}</section><section className='bg-slate-900 border border-slate-700 rounded-lg p-5'><h2 className='font-bold mb-4'>Herramientas</h2><button onClick={backup} className='px-4 py-2 bg-cyan-600 rounded text-sm'>Exportar respaldo SQLite</button><p className='text-xs text-slate-500 mt-3'>Primera capa web con SQLite local. Luego se puede conectar a una BD central Turso para multiusuario.</p></section></div></>}
function Products({products,query,setQuery,add}:any){return <><div className='flex items-center justify-between mb-4'><div><div className='text-2xl font-black'>Productos</div><div className='text-sm text-slate-400'>{products.length} registros</div></div><button className='px-3 py-2 rounded bg-cyan-600 text-sm flex items-center gap-2'><Plus size={16}/>Nuevo producto</button></div><div className='bg-slate-900 border border-slate-700 rounded-lg overflow-hidden'><div className='p-3 border-b border-slate-700 flex items-center gap-2'><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder='Código, nombre o categoría…' className='bg-transparent outline-none w-full text-sm'/></div><table className='w-full text-sm'><thead className='bg-slate-800 text-slate-400 text-xs uppercase'><tr><th className='text-left p-3'>Código</th><th className='text-left p-3'>Descripción</th><th className='text-left p-3'>Categoría</th><th className='text-right p-3'>Stock</th><th className='text-right p-3'>Precio USD</th><th></th></tr></thead><tbody>{products.map((p:Product)=><tr key={p.id} className='border-t border-slate-800'><td className='p-3 font-mono'>{p.code}</td><td className='p-3'>{p.name}</td><td className='p-3 text-slate-400'>{p.category}</td><td className='p-3 text-right'>{p.stock}</td><td className='p-3 text-right font-mono'>$ {p.priceUsd.toFixed(2)}</td><td className='p-3 text-right'><button onClick={()=>add(p)} className='text-cyan-300'>Vender</button></td></tr>)}</tbody></table></div></>}
function POS({cart,setCart,total,rate}:any){return <div className='h-full flex flex-col'><div className='flex items-center justify-between mb-4'><div><div className='text-2xl font-black'>Punto de Venta</div><div className='text-xs text-slate-400'>Caja Principal · Facturación</div></div><div className='text-right'><div className='text-xs text-slate-400'>TOTAL</div><div className='text-3xl font-black text-cyan-300 font-mono'>$ {total.toFixed(2)}</div><div className='text-xs text-slate-400'>Bs. {(total*rate).toFixed(2)}</div></div></div><div className='flex-1 grid lg:grid-cols-[1fr_360px] gap-4'><div className='bg-slate-900 border border-slate-700 rounded-lg flex items-center justify-center text-slate-500'>Seleccione productos desde <b className='mx-1 text-slate-300'>Productos</b>.</div><div className='bg-slate-900 border border-slate-700 rounded-lg overflow-hidden flex flex-col'><div className='p-3 border-b border-slate-700 font-bold'>Factura · {cart.length} ítems</div><div className='flex-1 overflow-auto'>{cart.map((p:Product,i:number)=><div className='p-3 border-b border-slate-800 flex gap-2' key={i}><div className='flex-1 text-sm'>{p.name}<div className='text-xs text-slate-500'>$ {p.priceUsd.toFixed(2)}</div></div><button onClick={()=>setCart((c:Product[])=>c.filter((_,j)=>j!==i))}><X size={15}/></button></div>)}</div><button disabled={!cart.length} className='m-3 py-3 rounded bg-emerald-600 disabled:bg-slate-700 disabled:text-slate-500 font-bold'>Cobrar $ {total.toFixed(2)}</button></div></div></div>}